### ISSUE TITLE
What people need from Rust

### ISSUE THREAD

**Issue by AngelOnFira** [rust-lang/ctcft#14]
**Who:** @nikomatsakis 

**General idea:** An analysis of reasons people use Rust and what works well (and doesn't work as well) when they do. Outcome from a series of conversations over the last few months.

**Which of the following categories apply:** (You can pick more than one!)

* [ ] Status update of broad interest
* [x] Experience report with insights to share
* [ ] Proposal for discussion

**What Rust teams would be interested in this and why?** Depending on the output format of this initiative (internal or open), all teams should benefit from these interviews.

**What kind of feedback are you looking for from the audience (if any)? Are there specific questions you'd like to ask?**

Potential questions:
- What might other teams want to know about how people are using Rust in prod

**Comment by nikomatsakis** [comment]
Going to close this until I have more specific idea.
