### ISSUE TITLE
Rust Skill Trees

### ISSUE THREAD

**Issue by AngelOnFira** [rust-lang/ctcft#19]
**Who:** @nikomatsakis 

**General idea:** Related to #14, [an example](https://nikomatsakis.github.io/rust-skill-tree/service-author.html)

**Which of the following categories apply:**

* [ ] Status update of broad interest
* [x] Experience report with insights to share
* [ ] Proposal for discussion

**What Rust teams would be interested in this and why?**

**What kind of feedback are you looking for from the audience (if any)? Are there specific questions you'd like to ask?**

**Comment by nikomatsakis** [comment]
I have to think if I have something solid to talk about here. I might! I've been having various conversations in/around AWS about people's experiences and what would help drive more usage of Rust, and there might be an interesting "case study" to present, but I'm not sure yet.

**Comment by AngelOnFira** [comment]
Might it be better to try and have #14 (What people need from Rust) this month, and save this for a future month?

**Comment by nikomatsakis** [comment]
Closing this and merging with #14
