### ISSUE TITLE
AUTOSAR, Rust in Automotive, requirements, Q&A

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/ctcft#28]
**Who:** @cpetig

**General idea:**
Inspired by https://www.autosar.org/news-events/details/autosar-announces-new-working-group-for-programming-language-rust-in-automotive-software-context-202/
Invite the Rust expert driving that effort to discuss their needs, requirements, and collaboration model, and have a long Q&A session.

**Which of the following categories apply:** (You can pick more than one!)

* [ ] Status update of broad interest
* [ ] Experience report with insights to share
* [X] Proposal for discussion

**What Rust teams would be intereted in this and why?**

Lang, libs, clippy: understanding requirements and potential standards being proposed.

**What kind of feedback are you looking for from the audience (if any)? Are there specific questions you'd like to ask?**

**Comment by ZhangHanDong** [comment]
This news has been withdrawn, does anyone know why?

**Comment by cpetig** [comment]
Thanks for raising the question, I will try to figure it out next week.
I can only confirm so far that the effort has gained good speed and to my knowledge hasn't been stopped.

**Comment by cpetig** [comment]
And @joshtriplett , I still have plenty of interest in a CTCFT track on autosar and/or functional safety, but I really need additional time to gather more material before voicing any non-obvious requirements on Rust. Right now Florian can probably offhand provide more material than I could.

**Comment by skade** [comment]
Happy to help there, maybe we want to have a co-presentation?

**Comment by cpetig** [comment]
@skade I would love to do it this way, your support is most appreciated. Thanks a lot! Feel free to contact me any time - and/or I will contact you when the next CTCFT comes close.

**Comment by joshtriplett** [comment]
@cpetig I definitely appreciate taking the time to gather material together, but also, for the purposes of the CTCFT I think it'd be appropriate to bring this while still fairly early. We'd love to hear what you're working on, and we'd love to ask lots of questions while you're still in the planning phase, rather than waiting until there's something further to show.

In particular, you don't have to *know* what requirements you'd want to place on Rust; I'd love to have a conversation about the general class of requirements you think you might potentially have, what goals they arise from, how those requirements might compare to standards for other languages, and so on.

**Comment by AngelOnFira** [comment]
Just a heads up, with April's theme of "learning", we've been looking at other talks for the upcoming CTCFT. This talk will be pushed back to a future month, but I'll be sure to reach out once we find a month whose theme it synergizes well with :100:

**Comment by drag0niro** [comment]
Did you already discuss the coding guidelines for Rust in automotive? Big companies in automotive industry love static code analysis reports with all kinds of intuitive metrics. For C and C++ we are mostly checking compliance for MISRA, AUTOSAR, CERT, CWE and few metrics like e.g. HIS. I guess for Rust to be widely accepted in the industry it has to come with similar guidelines or ensure a compliance with above ones.

**Comment by cpetig** [comment]
@drag0niro you might be looking for this https://connection.sae.org/volunteeropportunities/volunteer-opportunity-details?VolunteerOpportunityKey=057a92a9-c6b8-4405-ae81-e293136a9284 
or https://anssi-fr.github.io/rust-guide/ .
And of course the short answer is "Yes, we already started the discussion. Safe Rust should need few additional metrics to be considered compliant"

**Comment by cpetig** [comment]
> This news has been withdrawn, does anyone know why?

The news item is back, with slightly changed wording https://www.autosar.org/news-events/details/autosar-investigates-how-the-programming-language-rust-could-be-applied-in-adaptive-platform-context/

**Comment by ZhangHanDong** [comment]
@cpetig 

You can pay attention to this [Rust coding specification](https://rust-coding-guidelines.github.io/rust-coding-guidelines/), currently [the Chinese version](https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/) is more perfect, [the English version](https://rust-coding-guidelines.github.io/rust-coding-guidelines/) is being improved.

**Comment by AngelOnFira** [comment]
The theme for the May CTCFT is Embedded Rust, and I think this topic would be close enough to that theme that it could fit into this CTCFT. The CTCFT will take place at [11:00 EDT on the 16th of May](https://everytimezone.com/s/6c2a0d08), and we're looking at a 15-minute timeslot for now.

@cpetig @skade does this sound good?

**Comment by cpetig** [comment]
Yes, it does to me.

**Comment by AngelOnFira** [comment]
Great! When you have time, could I get a description and preferred title for the talk?

**Comment by skade** [comment]
@AngelOnFira I can do that, see you then!

**Comment by AngelOnFira** [comment]
Just want to ping again about getting a description for the blog posts :)

**Comment by AngelOnFira** [comment]
Blog post is live! https://blog.rust-lang.org/inside-rust/2022/05/10/CTCFT-may.html

**Comment by thebaron88** [comment]
Hi. Will a recording of the meeting be made available?
https://rust-lang.github.io/ctcft/meetings/2022-05-16.html currently just states "link posted after call". Thanks.

**Comment by dtolnay** [comment]
https://www.youtube.com/watch?v=MfG7OvfVYQY
