### ISSUE TITLE
Rustc Reading Club Phase II

### ISSUE THREAD

**Issue by doc-jones** [rust-lang/ctcft#29]
**Who:** @doc-jones

**General idea:** 
We have completed Rustc Reading Club (RRC) Phase I and have learned both from the experience and a participant retrospective. Now, we are ready to propose Phase II which is improved based on learning from Phase I.

**Theme**: Learning

**Which of the following categories apply:** (You can pick more than one!)

* [x] Status update of broad interest
* [ ] Experience report with insights to share
* [x] Proposal for discussion

**What Rust teams would be intereted in this and why?**
The Compiler Team as we are producing new contributors.
The rustc-dev-guide because we will be working through the guide and providing feedback or input where needed.
All Rust teams that are interested in trying the Reading Club model.

**What kind of feedback are you looking for from the audience (if any)? Are there specific questions you'd like to ask?**

**Comment by AngelOnFira** [comment]
@doc-jones this sounds good! We should be good to move forward with this talk for April. We'll have to see on the number of other speakers, but I would plan for a 15-minute timeslot (it might be 10 depending on who else we hear back from :+1:)
