### ISSUE TITLE
Embedded Rust

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/ctcft#30]
**Idea**: Embedded is a big growth area for Rust. Let's talk about it! 

Ideas for topics:

* Explain embedded to people in the Rust project so we understand better what embedded means\
* Walk through what's available now 
* Possible connections to rust teams: what would you need 

cc @rust-lang/wg-embedded-resources  (is this the right group to cc)

**Comment by jamesmunns** [comment]
Happy to chat/present whenever! Feel free to tag me or shoot me an email to schedule :)

**Comment by eldruin** [comment]
Nice idea!
cc. @rust-embedded/all

**Comment by AngelOnFira** [comment]
Alright, looks like we'll be moving ahead with this theme for May! I'll reach out in the other issues and make sure this works for the speakers :+1:

**Comment by hargoniX** [comment]
> Nice idea! cc. @rust-embedded/all EDIT: hmm, I cannot mention a foreign team here. We will announce this in our weekly meeting, though.

I did actually get a "team mention" so it does seem to work out, it's just not getting highlighted correctly.
