### ISSUE TITLE
Async in Embedded Rust

### ISSUE THREAD

**Issue by AngelOnFira** [rust-lang/ctcft#37]
**Who:** @Dirbaio

**General idea:** Progress and pain points of async in embedded Rust

**Theme**: Embedded Rust (#30)

**Which of the following categories apply:** (You can pick more than one!)

* [x] Status update of broad interest
* [x] Experience report with insights to share
* [ ] Proposal for discussion

**What Rust teams would be intereted in this and why?**

Async WG, various teams

**Comment by AngelOnFira** [comment]
@Dirbaio it looks like we'll do the Embedded Rust theme for May. The CTCFT will take place at [11:00 EDT on the 16th of May](https://everytimezone.com/s/6c2a0d08). We're looking at a 15-minute timeslot, as there are potentially 3 speakers this month. Let me know how this sounds!

**Comment by Dirbaio** [comment]
Sounds good, works for me! :+1:

**Comment by AngelOnFira** [comment]
Great! Also, if 15 minutes is too long, I can change it to a 10 minute slot :+1:

**Comment by AngelOnFira** [comment]
Also, once you get time, could I get a description of the talk and a preferred title?

**Comment by AngelOnFira** [comment]
Just want to ping again about getting a description for the blog posts :)

**Comment by Dirbaio** [comment]
**TItle**: Async Rust for embedded systems
**Description**: We'll explore how concurrency is traditionally handled in embedded, and how Rust's async makes it significantly easier while still requiring no runtime, no OS, and no allocation, and what Rust improvements could make it even more awesome.

**Comment by AngelOnFira** [comment]
Blog post is live! https://blog.rust-lang.org/inside-rust/2022/05/10/CTCFT-may.html

**Comment by AngelOnFira** [comment]
Thanks for the talk :)
