### ISSUE TITLE
State of Embedded Rust

### ISSUE THREAD

**Issue by AngelOnFira** [rust-lang/ctcft#38]
**Who:** @jamesmunns

**General idea:** The state of embedded Rust. Some possibly interesting topics might be where the difficulties are in the ecosystem, and what is the most effort going into right now.

**Theme**: Embedded Rust (#30)

**Which of the following categories apply:** (You can pick more than one!)

* [x] Status update of broad interest
* [ ] Experience report with insights to share
* [ ] Proposal for discussion

**What Rust teams would be interested in this and why?**

Lang, various

**Comment by jamesmunns** [comment]
Ah, thank you @AngelOnFira, this fell off my todo list! Let me know if there are any additional details or context I can fill in.

**Comment by AngelOnFira** [comment]
No worries :) I'll let you know once we confirm which month this will be a part of, and then verify that the time works for you :+1:

**Comment by AngelOnFira** [comment]
@jamesmunns we've selected the theme for May to be "Embedded Rust", so I just wanted to make sure that this works for you :smiley: The CTCFT will take place at [11:00 EDT on the 16th of May](https://everytimezone.com/s/6c2a0d08). We're looking at a 15-minute timeslot, as there are potentially 3 speakers this month. Let me know how this sounds!

**Comment by jamesmunns** [comment]
Sounds good to me, @AngelOnFira! I put it in my calendar, do I need a special invite/link for the event?

**Comment by jamesmunns** [comment]
Works perfectly for me!

**Comment by AngelOnFira** [comment]
Also, could I get a small description of the talk, and a preferred title?

**Comment by AngelOnFira** [comment]
Just want to ping again about getting a description for the blog posts :)

**Comment by jamesmunns** [comment]
Hey! So, I would say my title would be:

"A whirlwind tour of Embedded Rust", planning to cover:

* A brief history of the embedded-wg and use of Rust for embedded
* A look at how developing embedded rust looks like today
* A sample of patterns that are special to embedded rust, or differences from "desktop" Rust

**Comment by AngelOnFira** [comment]
Blog post is live! https://blog.rust-lang.org/inside-rust/2022/05/10/CTCFT-may.html

**Comment by AngelOnFira** [comment]
Thanks for the talk :)
